version: 2.1
jobs:
  buildit:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run : node --version
      - run: npm test
workflows:
  wf:
    jobs:
      - buildit
